# Generated by Django 2.2 on 2019-04-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='category1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname1', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname2', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='category3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname3', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='category4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname4', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
