# Generated by Django 2.2 on 2019-04-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('bookid', models.IntegerField(default=0)),
            ],
        ),
    ]
