# Generated by Django 2.2 on 2019-04-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='categoryname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
